# Generated by Django 5.2 on 2025-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.ImageField(upload_to=''),
        ),
    ]
